language: python
python:
  - "2.7"
  - "3.5"
  - pypy
# command to install dependencies
install: "pip install -r web/requirements.txt"
services:
  - mongodb
# command to run tests
script: cd web && python -m flask_rest_service.tests.core_tests && cd ..