language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy
  - pypy3
# command to install dependencies
install: "pip install -r web/requirements.txt"
services:
  - mongodb
before_script:
  - sleep 15
  - mongo mydb_test --eval 'db.addUser("travis", "test");'
# command to run tests
script: web/tests.py -v