# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PlanIt' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PlanIt
  pod ‘Alamofire’, ‘~> 4.0.1’
  pod 'SwiftyJSON'

  target 'PlanItTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PlanItUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
