#!/bin/bash

. ./scripts/exportvars.sh

./local_stop

bash ./scripts/installdeps.sh

echo "Removing existing database files"
rm -r "$dbpath"

echo "Creating clean database folders"
mkdir -p "$dbpath"

echo "Create logpath if not existing"
mkdir -p "$logpath"

echo "Starting mongo"
mongod --fork --logpath "$dblog" --port "$dbport" --dbpath "$dbpath"

echo "Waiting for mongod to run"
while ! nc -vz "$apihost" "$dbport"; do sleep 1; done
echo "Mongod successfully up"

echo "Running test server"
python "$testscript" &

echo "Waiting for the test server to run"
while ! nc -vz "$apihost" "$apiport"; do sleep 1; done
echo "Test server successfully up"
